# If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Just another blog
lang: en
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A web buffer to recall things that I know, or knew...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://greglan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: greglan3
github_username:  greglan
copyright:  © 2019. All rights reserved.

# Build settings
markdown: kramdown

incremental: true

# theme: minima
remote_theme: fongandrew/hydeout
# theme: jekyll-theme-hydeout
# theme: jekyll-theme-hacker
# theme: jekyll-theme-hyde
# remote_theme: poole/hyde

plugins:
  - jekyll-feed
  # - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

host: 0.0.0.0

collections:
  security:
    output: true
    permalink: /:collection/:name
  programming:
    output: true
    permalink: /:collection/:name
  networks:
    output: true
    permalink: /:collection/:name
  electronics:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "security"
    values:
      layout: page
  - scope:
      path: ""
      type: "programming"
    values:
      layout: page
  - scope:
      path: ""
      type: "networks"
    values:
      layout: page
  - scope:
      path: ""
      type: "electronics"
    values:
      layout: page
